export const categories = [
  {
    id: 'road',
    name: 'Road Bikes',
    slug: 'road',
    description: 'Built for speed, endurance, and the open road.',
    image: 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
    count: 12,
  },
  {
    id: 'mountain',
    name: 'Mountain Bikes',
    slug: 'mountain',
    description: 'Engineered for trails, gravel, and rugged terrain.',
    image: 'https://images.pexels.com/photos/1174103/pexels-photo-1174103.jpeg',
    count: 10,
  },
  {
    id: 'gravel',
    name: 'Gravel Bikes',
    slug: 'gravel',
    description: 'Versatile bikes ready for any adventure.',
    image: 'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg',
    count: 8,
  },
  {
    id: 'urban',
    name: 'Urban & City',
    slug: 'urban',
    description: 'Sleek designs crafted for city riding.',
    image: 'https://images.pexels.com/photos/1149601/pexels-photo-1149601.jpeg',
    count: 7,
  },
  {
    id: 'electric',
    name: 'Electric Bikes',
    slug: 'electric',
    description: 'Pedal-assisted performance with effortless range.',
    image: 'https://images.pexels.com/photos/9534620/pexels-photo-9534620.jpeg',
    count: 6,
  },
  {
    id: 'kids',
    name: "Kids' Bikes",
    slug: 'kids',
    description: 'Safe, fun, and built for young riders.',
    image: 'https://images.pexels.com/photos/1226398/pexels-photo-1226398.jpeg',
    count: 5,
  },
];

export const products = [
  {
    id: 'cosmic-apex-pro',
    name: 'Cosmic Apex Pro',
    slug: 'cosmic-apex-pro',
    category: 'road',
    categoryName: 'Road Bikes',
    price: 4299,
    originalPrice: 4799,
    description: 'The pinnacle of road cycling performance. Crafted with aerospace-grade carbon fiber and precision-engineered components for the discerning cyclist.',
    shortDescription: 'Aerospace carbon. Race-ready geometry. Legendary speed.',
    images: [
      'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
      'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
      'https://images.pexels.com/photos/3764154/pexels-photo-3764154.jpeg',
      'https://images.pexels.com/photos/2158963/pexels-photo-2158963.jpeg',
    ],
    badge: 'Best Seller',
    isNew: false,
    isFeatured: true,
    colors: ['Cosmic Black', 'Arctic White', 'Stellar Red'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    specs: {
      frame: 'T800 Carbon Fiber, Monocoque Construction',
      fork: 'Full Carbon, Tapered Steerer',
      groupset: 'Shimano Dura-Ace Di2 12-speed',
      brakes: 'Shimano Dura-Ace Hydraulic Disc',
      wheels: 'Cosmic Aero 50mm Carbon Clincher',
      tires: 'Continental GP 5000 TL 28c',
      weight: '7.1 kg (M size)',
      geometry: 'Race Endurance',
    },
    features: [
      'Ultra-light monocoque carbon frame',
      'Integrated cable routing system',
      'Aero-optimized tube profiles',
      'Electronic shifting precision',
      'Tubeless-ready wheelset',
    ],
    relatedAccessories: ['cosmic-aero-helmet', 'cosmic-pro-saddle', 'cosmic-carbon-bottle-cage'],
    relatedParts: ['cosmic-carbon-fork', 'shimano-dura-ace-groupset', 'cosmic-aero-wheels'],
  },
  {
    id: 'cosmic-terra-elite',
    name: 'Cosmic Terra Elite',
    slug: 'cosmic-terra-elite',
    category: 'mountain',
    categoryName: 'Mountain Bikes',
    price: 3799,
    originalPrice: null,
    description: 'Conquer every trail with confidence. The Terra Elite blends aggressive geometry with supreme compliance for trail and enduro riding.',
    shortDescription: 'Full-suspension trail mastery. Born to dominate.',
    images: [
      'https://plus.unsplash.com/premium_photo-1713184149457-ce10583b4ccd?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8cm9hZCUyMGJpa2V8ZW58MHx8MHx8fDA%3D',
      'https://images.pexels.com/photos/2305540/pexels-photo-2305540.jpeg',
      'https://images.pexels.com/photos/3760529/pexels-photo-3760529.jpeg',
      'https://images.pexels.com/photos/1009101/pexels-photo-1009101.jpeg',
    ],
    badge: 'New',
    isNew: true,
    isFeatured: true,
    colors: ['Forest Green', 'Midnight Black', 'Desert Sand'],
    sizes: ['S', 'M', 'L', 'XL'],
    specs: {
      frame: 'Hydroformed Aluminum, 140mm Travel',
      fork: 'RockShox Pike Ultimate 140mm',
      groupset: 'Shimano XT 12-speed',
      brakes: 'Shimano XT 4-Piston Hydraulic',
      wheels: 'DT Swiss XM 1700 29"',
      tires: 'Maxxis Minion DHF 2.5" / DHR II 2.4"',
      weight: '13.8 kg (M size)',
      geometry: 'Trail/Enduro',
    },
    features: [
      'Progressive link geometry for precise handling',
      'Adjustable head angle flip chip',
      'Boost 148mm rear spacing',
      'Integrated downtube storage',
      'Dropper post compatible',
    ],
    relatedAccessories: ['cosmic-trail-helmet', 'cosmic-mtb-gloves', 'cosmic-hydration-pack'],
    relatedParts: ['rockshox-pike-fork', 'shimano-xt-cassette', 'maxxis-trail-tires'],
  },
  {
    id: 'cosmic-venture-gravel',
    name: 'Cosmic Venture Gravel',
    slug: 'cosmic-venture-gravel',
    category: 'gravel',
    categoryName: 'Gravel Bikes',
    price: 2899,
    originalPrice: 3199,
    description: 'Built for the explorers. The Venture Gravel merges road efficiency with off-road capability, taking you further into the unknown.',
    shortDescription: 'Explore more. Stop less. The ultimate adventure companion.',
    images: [
      'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg',
      'https://images.pexels.com/photos/1103529/pexels-photo-1103529.jpeg',
      'https://images.pexels.com/photos/2158963/pexels-photo-2158963.jpeg',
      'https://images.pexels.com/photos/3764154/pexels-photo-3764154.jpeg',
    ],
    badge: 'Sale',
    isNew: false,
    isFeatured: true,
    colors: ['Gravel Grey', 'Burnt Orange', 'Cosmic Blue'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    specs: {
      frame: 'T700 Carbon Fiber, Endurance Geometry',
      fork: 'Cosmic Carbon Gravel Fork',
      groupset: 'SRAM Rival AXS 12-speed',
      brakes: 'SRAM Rival Hydraulic Disc',
      wheels: 'WTB ST i23 650b',
      tires: 'WTB Riddler 45c Tubeless',
      weight: '8.6 kg (M size)',
      geometry: 'Adventure Endurance',
    },
    features: [
      'Mounts for bags and fenders',
      'Wide clearance for 45c tires',
      'Internal cable routing',
      'Flared handlebars for control',
      'Three bottle cage mounts',
    ],
    relatedAccessories: ['cosmic-gravel-bag', 'cosmic-adventure-kit', 'cosmic-navigation-mount'],
    relatedParts: ['wtb-gravel-tires', 'sram-rival-axs', 'wtb-gravel-wheels'],
  },
  {
    id: 'cosmic-metro-s',
    name: 'Cosmic Metro S',
    slug: 'cosmic-metro-s',
    category: 'urban',
    categoryName: 'Urban & City',
    price: 1499,
    originalPrice: null,
    description: 'City sophistication meets cycling functionality. The Metro S is designed for the urban professional who refuses to compromise on style or performance.',
    shortDescription: 'Refined. Elegant. Your city in a new light.',
    images: [
      'https://images.pexels.com/photos/1149601/pexels-photo-1149601.jpeg',
      'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
      'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
      'https://images.pexels.com/photos/2158963/pexels-photo-2158963.jpeg',
    ],
    badge: null,
    isNew: false,
    isFeatured: false,
    colors: ['Matte Black', 'Pearl White', 'Cobalt Blue'],
    sizes: ['S', 'M', 'L'],
    specs: {
      frame: '6061 Aluminum, City Geometry',
      fork: 'Steel, Smooth Ride',
      groupset: 'Shimano Nexus 8-speed Internal',
      brakes: 'Shimano Hydraulic Disc',
      wheels: 'Alex DC19 700c',
      tires: 'Schwalbe Marathon Plus 35c',
      weight: '11.2 kg',
      geometry: 'Upright City',
    },
    features: [
      'Integrated rear rack mount',
      'Dynamo lighting compatible',
      'Puncture-resistant tires',
      'Fender mounts included',
      'Ergonomic swept-back bars',
    ],
    relatedAccessories: ['cosmic-city-bag', 'cosmic-lock', 'cosmic-city-fenders'],
    relatedParts: ['shimano-nexus-hub', 'marathon-plus-tires', 'city-fenders'],
  },
  {
    id: 'cosmic-flux-e',
    name: 'Cosmic Flux E',
    slug: 'cosmic-flux-e',
    category: 'electric',
    categoryName: 'Electric Bikes',
    price: 5999,
    originalPrice: null,
    description: 'Harness the power of precision electronics and Cosmic engineering. The Flux E delivers exhilarating e-bike performance without compromising on design.',
    shortDescription: 'Amplify your ride. Zero compromise, maximum range.',
    images: [
      'https://wallpapercave.com/wp/wp8977246.jpg',
      'https://images.pexels.com/photos/1174103/pexels-photo-1174103.jpeg',
      'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg',
      'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
    ],
    badge: 'Featured',
    isNew: true,
    isFeatured: true,
    colors: ['Carbon Black', 'Glacier White'],
    sizes: ['S', 'M', 'L', 'XL'],
    specs: {
      frame: 'Custom E-Bike Carbon Fiber',
      motor: 'Bosch Performance Line CX 85Nm',
      battery: '750Wh Integrated PowerTube',
      range: 'Up to 160km (Eco mode)',
      display: 'Kiox 300 Color Display',
      groupset: 'Shimano Deore 12-speed',
      brakes: 'Magura MT5e 4-Piston',
      weight: '22.5 kg',
    },
    features: [
      'Integrated battery concealed in downtube',
      'Walk assist mode',
      'Smartphone connectivity via eBike Flow App',
      'Automatic mode (ABS) braking',
      'Remote charging capability',
    ],
    relatedAccessories: ['cosmic-e-helmet', 'cosmic-e-lock', 'cosmic-charger-bag'],
    relatedParts: ['bosch-battery', 'bosch-motor-unit', 'magura-brake-pads'],
  },
  {
    id: 'cosmic-bolt-junior',
    name: 'Cosmic Bolt Junior',
    slug: 'cosmic-bolt-junior',
    category: 'kids',
    categoryName: "Kids' Bikes",
    price: 499,
    originalPrice: 599,
    description: "Inspire the next generation of riders with a bike built for confidence, safety, and fun. The Bolt Junior is a kid's bike that doesn't compromise.",
    shortDescription: "Lightweight, safe, and made for adventure.",
    images: [
      'https://images.pexels.com/photos/1226398/pexels-photo-1226398.jpeg',
      'https://images.pexels.com/photos/1149601/pexels-photo-1149601.jpeg',
      'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
      'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg',
    ],
    badge: 'Sale',
    isNew: false,
    isFeatured: false,
    colors: ['Rocket Red', 'Galaxy Blue', 'Nebula Green'],
    sizes: ['20"', '24"'],
    specs: {
      frame: 'Ultra-light Aluminum',
      fork: 'Alloy, Rigid',
      groupset: 'Shimano Acera 8-speed',
      brakes: 'Tektro Hydraulic Disc',
      wheels: 'Alex MD19 24"',
      tires: 'Kenda Booster 24x2.0"',
      weight: '9.2 kg',
      ageRange: '8-14 years',
    },
    features: [
      'Child-proportioned geometry',
      'Easy-pull brake levers',
      'Lightweight tubeless-ready rims',
      'Adjustable saddle and bars',
      'Fun color options',
    ],
    relatedAccessories: ['cosmic-kids-helmet', 'cosmic-kids-gloves', 'cosmic-kids-bottle'],
    relatedParts: ['kids-brake-cable', 'kids-saddle', 'kids-stem'],
  },
  {
    id: 'cosmic-apex-sl',
    name: 'Cosmic Apex SL',
    slug: 'cosmic-apex-sl',
    category: 'road',
    categoryName: 'Road Bikes',
    price: 6499,
    originalPrice: null,
    description: 'The lightest bike we have ever made. The Apex SL is a tour de force in carbon engineering, designed for climbing specialists and weight-conscious racers.',
    shortDescription: 'Sub-700g frame. Climbing legend. Apex of speed.',
    images: [
      'https://wallpapercave.com/wp/wp6045030.jpg',
      'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
      'https://images.pexels.com/photos/3764154/pexels-photo-3764154.jpeg',
      'https://images.pexels.com/photos/2158963/pexels-photo-2158963.jpeg',
    ],
    badge: 'Limited',
    isNew: true,
    isFeatured: true,
    colors: ['Ghost White', 'Carbon Raw'],
    sizes: ['XS', 'S', 'M', 'L'],
    specs: {
      frame: 'UD Carbon Monocoque, 695g',
      fork: 'Full UD Carbon, 265g',
      groupset: 'Shimano Dura-Ace Di2 12-speed',
      brakes: 'Shimano Dura-Ace Hydraulic',
      wheels: 'Cosmic Ultra 35mm Carbon Tubeless',
      tires: 'Continental GP TT 25c',
      weight: '6.4 kg (M size)',
      geometry: 'Pure Race',
    },
    features: [
      'Sub-700g frame weight',
      'One-piece cockpit system',
      'Asymmetric stay design for stiffness',
      'Wind-tunnel optimized tube shapes',
      'Limited production run',
    ],
    relatedAccessories: ['cosmic-aero-helmet', 'cosmic-pro-saddle', 'cosmic-carbon-bottle-cage'],
    relatedParts: ['cosmic-carbon-fork', 'shimano-dura-ace-groupset', 'cosmic-ultra-wheels'],
  },
  {
    id: 'cosmic-ridge-xt',
    name: 'Cosmic Ridge XT',
    slug: 'cosmic-ridge-xt',
    category: 'gravel',
    categoryName: 'Gravel Bikes',
    price: 3499,
    originalPrice: null,
    description: 'The ultimate long-distance gravel machine. The Ridge XT is built for bikepacking adventures, loaded touring, and weeks in the saddle.',
    shortDescription: 'Bikepacking ready. Built for the long haul.',
    images: [
      'https://images.pexels.com/photos/1103529/pexels-photo-1103529.jpeg',
      'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg',
      'https://images.pexels.com/photos/2158963/pexels-photo-2158963.jpeg',
      'https://images.pexels.com/photos/3764154/pexels-photo-3764154.jpeg',
    ],
    badge: 'New',
    isNew: true,
    isFeatured: false,
    colors: ['Expedition Green', 'Desert Tan', 'Night Sky'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    specs: {
      frame: 'Steel/Carbon Hybrid, Touring Geometry',
      fork: 'Carbon with Lowrider Mounts',
      groupset: 'SRAM GRX 820 12-speed',
      brakes: 'SRAM GRX Hydraulic Flat Mount',
      wheels: 'Hunt 4 Season Gravel XT 700c',
      tires: 'Panaracer GravelKing SK 40c',
      weight: '9.8 kg',
      geometry: 'Bikepacking/Touring',
    },
    features: [
      'Multiple mounting points for bags',
      'Low-trail geometry for loaded handling',
      'Clearance for 50c tires',
      'Thru-axle front and rear',
      'Internal dynamo routing',
    ],
    relatedAccessories: ['cosmic-frame-bag', 'cosmic-handlebar-bag', 'cosmic-saddle-bag'],
    relatedParts: ['sram-grx-groupset', 'panaracer-gravel-tires', 'hunt-gravel-wheels'],
  },
];

export const accessories = [
  {
    id: 'cosmic-aero-helmet',
    name: 'Cosmic Aero Helmet',
    slug: 'cosmic-aero-helmet',
    category: 'helmets',
    categoryName: 'Helmets',
    price: 349,
    originalPrice: null,
    description: 'Wind-tunnel tested aerodynamic helmet with MIPS protection system. Perfect for road and triathlon racing.',
    shortDescription: 'Aero. Protected. Fast.',
    image: 'https://images.pexels.com/photos/3752391/pexels-photo-3752391.jpeg',
    badge: 'Best Seller',
    specs: { weight: '280g', certification: 'CE EN1078, CPSC', ventilation: '12 vents' },
  },
  {
    id: 'cosmic-trail-helmet',
    name: 'Cosmic Trail Helmet',
    slug: 'cosmic-trail-helmet',
    category: 'helmets',
    categoryName: 'Helmets',
    price: 249,
    originalPrice: 299,
    description: 'Full-featured trail helmet with MIPS and adjustable visor. Built for mountain and adventure riding.',
    shortDescription: 'MIPS protection meets trail-ready design.',
    image: 'https://images.pexels.com/photos/4397840/pexels-photo-4397840.jpeg',
    badge: 'Sale',
    specs: { weight: '340g', certification: 'CE EN1078', ventilation: '20 vents' },
  },
  {
    id: 'cosmic-pro-saddle',
    name: 'Cosmic Pro Saddle',
    slug: 'cosmic-pro-saddle',
    category: 'saddles',
    categoryName: 'Saddles',
    price: 189,
    originalPrice: null,
    description: 'Race-tuned carbon rail saddle with pressure-relief channel. Ideal for long road and endurance riding.',
    shortDescription: 'Carbon rails. Endurance comfort.',
    image: 'https://images.pexels.com/photos/5591663/pexels-photo-5591663.jpeg',
    badge: null,
    specs: { weight: '198g', rails: 'Carbon', width: '143mm / 155mm' },
  },
  {
    id: 'cosmic-carbon-bottle-cage',
    name: 'Carbon Bottle Cage',
    slug: 'cosmic-carbon-bottle-cage',
    category: 'accessories',
    categoryName: 'Accessories',
    price: 49,
    originalPrice: null,
    description: 'Ultra-light carbon fiber bottle cage compatible with all standard water bottles.',
    shortDescription: 'Ultra-light carbon. Secure grip.',
    image: 'https://images.pexels.com/photos/3764154/pexels-photo-3764154.jpeg',
    badge: null,
    specs: { weight: '22g', material: 'UD Carbon', compatibility: 'Standard bottles' },
  },
  {
    id: 'cosmic-mtb-gloves',
    name: 'MTB Pro Gloves',
    slug: 'cosmic-mtb-gloves',
    category: 'apparel',
    categoryName: 'Apparel',
    price: 79,
    originalPrice: null,
    description: 'Padded trail gloves with silicone grip and touchscreen-compatible fingers. Built for rough terrain.',
    shortDescription: 'Grip. Protection. Control.',
    image: 'https://images.pexels.com/photos/4397840/pexels-photo-4397840.jpeg',
    badge: null,
    specs: { padding: 'Gel palmpad', grip: 'Silicone', closure: 'Velcro' },
  },
  {
    id: 'cosmic-hydration-pack',
    name: 'Cosmic Hydration Pack',
    slug: 'cosmic-hydration-pack',
    category: 'bags',
    categoryName: 'Bags & Packs',
    price: 129,
    originalPrice: 149,
    description: '10L hydration pack with 2L reservoir and integrated tool organization for trail and enduro riding.',
    shortDescription: '10L trail pack. 2L reservoir included.',
    image: 'https://images.pexels.com/photos/5591663/pexels-photo-5591663.jpeg',
    badge: 'Sale',
    specs: { capacity: '10L + 2L reservoir', back: 'Ventilated mesh', hip: 'Stabilizer hip belt' },
  },
  {
    id: 'cosmic-gravel-bag',
    name: 'Cosmic Gravel Frame Bag',
    slug: 'cosmic-gravel-bag',
    category: 'bags',
    categoryName: 'Bags & Packs',
    price: 89,
    originalPrice: null,
    description: 'Medium frame bag designed for gravel bikes. Water-resistant with magnetic closure and tool pouch.',
    shortDescription: 'Water-resistant frame bag for adventures.',
    image: 'https://images.pexels.com/photos/3764154/pexels-photo-3764154.jpeg',
    badge: null,
    specs: { capacity: '2.5L', material: 'TPU-coated nylon', closure: 'Magnetic + velcro' },
  },
  {
    id: 'cosmic-city-bag',
    name: 'Cosmic City Pannier',
    slug: 'cosmic-city-bag',
    category: 'bags',
    categoryName: 'Bags & Packs',
    price: 149,
    originalPrice: null,
    description: 'Convertible 20L city pannier that transforms into a backpack. Fits 15" laptop, waterproof exterior.',
    shortDescription: 'Pannier to backpack in seconds.',
    image: 'https://images.pexels.com/photos/5591663/pexels-photo-5591663.jpeg',
    badge: 'New',
    specs: { capacity: '20L', laptop: '15" sleeve', waterproof: 'IPX4 rated' },
  },
];

export const spareParts = [
  {
    id: 'cosmic-carbon-fork',
    name: 'Cosmic Carbon Road Fork',
    slug: 'cosmic-carbon-fork',
    category: 'forks',
    categoryName: 'Forks',
    price: 399,
    description: 'Full carbon road fork, tapered steerer, 47mm rake. Compatible with all Cosmic road frames.',
    image: 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
    compatibility: 'Cosmic Apex Series, Cosmic Venture',
    sku: 'CSM-FK-C001',
  },
  {
    id: 'shimano-dura-ace-groupset',
    name: 'Shimano Dura-Ace Di2 Groupset',
    slug: 'shimano-dura-ace-groupset',
    category: 'groupsets',
    categoryName: 'Groupsets',
    price: 1899,
    description: 'Complete Shimano Dura-Ace R9200 Di2 12-speed electronic groupset including derailleurs, shifters, and brakes.',
    image: 'https://images.pexels.com/photos/1571939/pexels-photo-1571939.jpeg',
    compatibility: 'Cosmic Apex Pro, Cosmic Apex SL',
    sku: 'SHM-DA-R9200',
  },
  {
    id: 'cosmic-aero-wheels',
    name: 'Cosmic Aero 50mm Carbon Wheelset',
    slug: 'cosmic-aero-wheels',
    category: 'wheels',
    categoryName: 'Wheels',
    price: 1299,
    description: '50mm full carbon clincher wheelset. Tubeless-ready with Cosmic precision hubs. Wind-tunnel tested.',
    image: 'https://images.pexels.com/photos/3764154/pexels-photo-3764154.jpeg',
    compatibility: 'All Cosmic Road Bikes',
    sku: 'CSM-WH-A050',
  },
  {
    id: 'rockshox-pike-fork',
    name: 'RockShox Pike Ultimate 140mm',
    slug: 'rockshox-pike-fork',
    category: 'suspension',
    categoryName: 'Suspension',
    price: 749,
    description: 'RockShox Pike Ultimate trail fork with Charger 3 RC2 damper. 140mm travel, Boost spacing.',
    image: 'https://images.pexels.com/photos/1174103/pexels-photo-1174103.jpeg',
    compatibility: 'Cosmic Terra Elite',
    sku: 'RSX-PK-U140',
  },
  {
    id: 'shimano-xt-cassette',
    name: 'Shimano XT 10-51T Cassette',
    slug: 'shimano-xt-cassette',
    category: 'drivetrain',
    categoryName: 'Drivetrain',
    price: 129,
    description: 'Shimano Deore XT M8100 12-speed cassette, 10-51T. Hyperglide+ chain technology.',
    image: 'https://images.pexels.com/photos/2305540/pexels-photo-2305540.jpeg',
    compatibility: 'Cosmic Terra Elite, Shimano 12-speed',
    sku: 'SHM-XT-C1051',
  },
  {
    id: 'maxxis-trail-tires',
    name: 'Maxxis Minion DHF 2.5" (pair)',
    slug: 'maxxis-trail-tires',
    category: 'tires',
    categoryName: 'Tires',
    price: 119,
    description: 'Set of two Maxxis Minion DHF 3C MaxxTerra EXO tires. 29x2.5" tubeless-ready.',
    image: 'https://images.pexels.com/photos/1009101/pexels-photo-1009101.jpeg',
    compatibility: 'Cosmic Terra Elite, 29" MTB',
    sku: 'MXS-DHF-29',
  },
  {
    id: 'sram-rival-axs',
    name: 'SRAM Rival AXS XPLR Groupset',
    slug: 'sram-rival-axs',
    category: 'groupsets',
    categoryName: 'Groupsets',
    price: 999,
    description: 'SRAM Rival AXS XPLR 12-speed wireless electronic groupset. Gravel-optimized with 44T max chainring.',
    image: 'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg',
    compatibility: 'Cosmic Venture Gravel',
    sku: 'SRM-RVL-AXS',
  },
  {
    id: 'wtb-gravel-wheels',
    name: 'WTB Proterra Light 650b Wheelset',
    slug: 'wtb-gravel-wheels',
    category: 'wheels',
    categoryName: 'Wheels',
    price: 599,
    description: 'WTB Proterra Light 650b wheelset with i23 rim profile. Tubeless-ready, 28h front/rear.',
    image: 'https://images.pexels.com/photos/1103529/pexels-photo-1103529.jpeg',
    compatibility: 'Cosmic Venture Gravel, Cosmic Ridge XT',
    sku: 'WTB-PL-650',
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'James Harrington',
    role: 'Amateur Road Racer',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg',
    text: "The Cosmic Apex Pro transformed my riding completely. The carbon frame absorbs road buzz effortlessly while still delivering incredible stiffness when I sprint. It's the finest bike I've ever ridden.",
    bike: 'Cosmic Apex Pro',
    rating: 5,
  },
  {
    id: 2,
    name: 'Sarah Nguyen',
    role: 'Trail Rider & Instructor',
    avatar: 'https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg',
    text: "I put the Terra Elite through everything — rock gardens, steep chutes, muddy roots. It handles everything with confidence and composure. The geometry is perfect for both descending and climbing.",
    bike: 'Cosmic Terra Elite',
    rating: 5,
  },
  {
    id: 3,
    name: 'Marcus Webb',
    role: 'Bikepacker & Adventurer',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg',
    text: "Done 4,000km on the Ridge XT loaded with 18kg of gear. The bike never complained. Handling is intuitive even fully loaded, and the frame geometry just inspires confidence mile after mile.",
    bike: 'Cosmic Ridge XT',
    rating: 5,
  },
  {
    id: 4,
    name: 'Priya Mehta',
    role: 'Urban Commuter',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg',
    text: "The Metro S is the perfect city bike. It looks stunning, rides smoothly, and the internal gearing is maintenance-free. I get compliments at every stop light. Couldn't be happier.",
    bike: 'Cosmic Metro S',
    rating: 5,
  },
];

export const dealers = [
  {
    id: 1,
    name: 'Cosmic Flagship Store - Mumbai',
    address: '22, Bandra-Kurla Complex, Mumbai, Maharashtra 400051',
    city: 'Mumbai',
    state: 'Maharashtra',
    phone: '+91 22 6789 1234',
    email: 'mumbai@cosmicbikes.com',
    type: 'Flagship',
    hours: 'Mon-Sat 10am-8pm, Sun 11am-6pm',
  },
  {
    id: 2,
    name: 'Cosmic Dealer - Pune',
    address: '14, Koregaon Park, Pune, Maharashtra 411001',
    city: 'Pune',
    state: 'Maharashtra',
    phone: '+91 20 2567 8901',
    email: 'pune@cosmicbikes.com',
    type: 'Dealer',
    hours: 'Mon-Sat 9:30am-7:30pm',
  },
  {
    id: 3,
    name: 'Cosmic Experience Centre - Bangalore',
    address: '87, Indiranagar 100ft Road, Bangalore, Karnataka 560038',
    city: 'Bangalore',
    state: 'Karnataka',
    phone: '+91 80 4567 8901',
    email: 'bangalore@cosmicbikes.com',
    type: 'Experience Centre',
    hours: 'Tue-Sun 10am-7pm',
  },
  {
    id: 4,
    name: 'Cosmic Dealer - Chennai',
    address: '5, Anna Salai, Teynampet, Chennai, Tamil Nadu 600018',
    city: 'Chennai',
    state: 'Tamil Nadu',
    phone: '+91 44 2890 1234',
    email: 'chennai@cosmicbikes.com',
    type: 'Dealer',
    hours: 'Mon-Sat 10am-8pm',
  },
  {
    id: 5,
    name: 'Cosmic Flagship Store - Delhi',
    address: '34, Connaught Place, New Delhi 110001',
    city: 'New Delhi',
    state: 'Delhi',
    phone: '+91 11 4567 9012',
    email: 'delhi@cosmicbikes.com',
    type: 'Flagship',
    hours: 'Mon-Sun 10am-9pm',
  },
  {
    id: 6,
    name: 'Cosmic Dealer - Hyderabad',
    address: '78, Jubilee Hills, Hyderabad, Telangana 500033',
    city: 'Hyderabad',
    state: 'Telangana',
    phone: '+91 40 3456 7890',
    email: 'hyderabad@cosmicbikes.com',
    type: 'Dealer',
    hours: 'Mon-Sat 10am-7pm',
  },
  {
    id: 7,
    name: 'Cosmic Dealer - Ahmedabad',
    address: '123, SG Highway, Prahlad Nagar, Ahmedabad, Gujarat 380015',
    city: 'Ahmedabad',
    state: 'Gujarat',
    phone: '+91 79 2678 9012',
    email: 'ahmedabad@cosmicbikes.com',
    type: 'Dealer',
    hours: 'Mon-Sat 9am-7pm',
  },
  {
    id: 8,
    name: 'Cosmic Dealer - Kolkata',
    address: '9, Park Street, Kolkata, West Bengal 700016',
    city: 'Kolkata',
    state: 'West Bengal',
    phone: '+91 33 2234 5678',
    email: 'kolkata@cosmicbikes.com',
    type: 'Dealer',
    hours: 'Mon-Sat 10am-7:30pm',
  },
];

export const careers = [
  {
    id: 1,
    title: 'Senior Product Designer',
    department: 'Design & Engineering',
    location: 'Mumbai, Maharashtra',
    type: 'Full-time',
    experience: '5+ years',
    posted: '2026-05-01',
    description: 'Lead the design of next-generation Cosmic bicycle models, from concept sketches through to production-ready specifications. Work closely with our engineering, marketing, and manufacturing teams.',
    responsibilities: [
      'Drive the full product design lifecycle from concept to production',
      'Develop and maintain design language across all Cosmic product lines',
      'Collaborate with engineers on structural and functional design solutions',
      'Conduct user research and rider testing programs',
      'Present concepts to senior leadership and stakeholders',
    ],
    requirements: [
      '5+ years industrial design experience, preferably in cycling or sporting goods',
      'Proficiency in SolidWorks, Rhino, and Adobe Creative Suite',
      'Deep understanding of bicycle mechanics and materials',
      "Bachelor's degree in Industrial Design or equivalent",
      'Strong portfolio demonstrating product design skills',
    ],
  },
  {
    id: 2,
    title: 'Marketing Manager - Digital',
    department: 'Marketing',
    location: 'Mumbai, Maharashtra',
    type: 'Full-time',
    experience: '4+ years',
    posted: '2026-05-05',
    description: "Lead Cosmic's digital marketing strategy across social media, paid advertising, email marketing, and content creation. Drive brand awareness and customer acquisition in key markets.",
    responsibilities: [
      'Own and execute the digital marketing roadmap',
      'Manage paid media budgets across Google, Meta, and YouTube',
      'Lead content strategy and brand storytelling',
      'Analyze campaign performance and optimize for ROI',
      'Collaborate with retail partners on co-marketing programs',
    ],
    requirements: [
      '4+ years digital marketing experience',
      'Strong command of paid social and search platforms',
      'Experience in premium consumer brands preferred',
      'Data-driven mindset with expertise in analytics tools',
      'Excellent communication and presentation skills',
    ],
  },
  {
    id: 3,
    title: 'Mechanical Engineer - Frame Development',
    department: 'Engineering',
    location: 'Pune, Maharashtra',
    type: 'Full-time',
    experience: '3-6 years',
    posted: '2026-04-28',
    description: 'Join our frame development team to design and validate carbon fiber and aluminum bicycle frames. You will use FEA simulation, prototype testing, and manufacturing optimization to bring cutting-edge bikes to life.',
    responsibilities: [
      'Design and develop frame geometry and structural layouts',
      'Conduct FEA analysis and prototype testing programs',
      'Coordinate with manufacturing suppliers on tooling and processes',
      'Document engineering specifications and test reports',
      'Support product certification and compliance activities',
    ],
    requirements: [
      "Bachelor's or Master's in Mechanical Engineering",
      'Experience with FEA tools (ANSYS, Abaqus)',
      'Knowledge of carbon fiber fabrication processes',
      'Proficiency in CAD (CATIA, SolidWorks)',
      'Passion for cycling is a plus',
    ],
  },
  {
    id: 4,
    title: 'Retail Sales Specialist',
    department: 'Sales & Retail',
    location: 'Bangalore, Karnataka',
    type: 'Full-time',
    experience: '2+ years',
    posted: '2026-05-10',
    description: 'Be the face of Cosmic at our Bangalore Experience Centre. Help customers find their perfect ride through expert consultation, test ride coordination, and personalized service.',
    responsibilities: [
      'Provide expert product consultation to walk-in customers',
      'Conduct test ride sessions and fitting appointments',
      'Achieve monthly sales targets across the product range',
      'Maintain store presentation and inventory standards',
      'Build long-term relationships with the local cycling community',
    ],
    requirements: [
      '2+ years retail or sales experience',
      'Deep knowledge of bicycles and cycling culture',
      'Excellent interpersonal and communication skills',
      'Ability to work weekends and public holidays',
      'Fluent in English and Kannada preferred',
    ],
  },
  {
    id: 5,
    title: 'Supply Chain & Logistics Coordinator',
    department: 'Operations',
    location: 'Mumbai, Maharashtra',
    type: 'Full-time',
    experience: '3+ years',
    posted: '2026-05-08',
    description: 'Manage inbound and outbound logistics for Cosmic operations, coordinating with suppliers, freight partners, and our dealer network to ensure smooth product availability.',
    responsibilities: [
      'Coordinate import/export logistics for components and finished goods',
      'Manage relationships with freight forwarders and customs brokers',
      'Monitor inventory levels and flag potential shortfalls',
      'Optimize transportation costs and lead times',
      'Support ERP implementation and process improvement projects',
    ],
    requirements: [
      '3+ years supply chain or logistics experience',
      'Knowledge of import/export regulations and customs procedures',
      'Experience with ERP or inventory management systems',
      'Strong Excel and data analysis skills',
      "Bachelor's degree in Supply Chain, Business, or related field",
    ],
  },
];

export const warrantyFaqs = [
  {
    question: 'What is covered under the Cosmic warranty?',
    answer: "Cosmic frames and forks are covered by a lifetime warranty against manufacturing defects for the original owner. Components (groupsets, wheels, saddles, etc.) are covered for 2 years. This warranty does not cover crash damage, wear and tear, improper use, or modifications.",
  },
  {
    question: 'How do I register my Cosmic bike for warranty?',
    answer: 'Register your bike within 30 days of purchase using the serial number found on the bottom bracket shell. You can register online through our website or at your authorized Cosmic dealer.',
  },
  {
    question: 'Can I transfer the warranty if I sell my bike?',
    answer: 'Frame and fork lifetime warranty is non-transferable and applies to the original registered owner only. Component warranties may transfer with proof of purchase.',
  },
  {
    question: 'What should I do if I discover a defect?',
    answer: 'Stop riding the bike immediately if you suspect a structural defect. Contact your nearest authorized Cosmic dealer or reach our support team with photos and your serial number. Do not attempt to repair a defective frame.',
  },
  {
    question: 'How long does a warranty claim take to process?',
    answer: 'Warranty claims are reviewed within 5-7 business days upon receipt of all required information. Replacement or repair turnaround time varies by availability, typically 2-4 weeks.',
  },
  {
    question: 'What is not covered by the warranty?',
    answer: 'Crash damage, corrosion from improper storage, worn components (brake pads, chains, tires), damage from improper assembly or maintenance, paint chips, and modifications by unauthorized service centers are not covered.',
  },
];
